//Redux Action & Reducer Case Types

export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const LANGUAGE_TRANSLATE = "LANGUAGE_TRANSLATE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGGED_OUT = "LOGGED_OUT";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_LOADER = "SET_LOADER";
export const SEARCHING_REQUEST = "SEARCHING_REQUEST";
export const SEARCHING_SUCCESS = "SEARCHING_SUCCESS";
export const SET_FILTER_DROPDOWN_TAGS = "SET_FILTER_DROPDOWN_TAGS";
export const REPORT_PDF_SUCCESS = "REPORT_PDF_SUCCESS";
